### ISSUE TITLE
Reference error: eventName is not defined in fromSgf->setInfo->setEventLocation

### ISSUE THREAD

**Issue by bobthemighty** [adamreisnz/seki#3]
Hello!

The slides I put together are broken. I've check sekigoplayer.com and you have the same issue on the game boards page affecting the `19x19 (replay game record)` example. There are some other boards there that don't render at all, plausibly for the same reason.

```
Uncaught (in promise) ReferenceError: eventName is not defined
    at F.setEventLocation (seki-embed.js:4126:87)
    at F.setInfo (seki-embed.js:4018:381)
    at vr.convert (seki-embed.js:3492:14)
    at F.fromSgf (seki-embed.js:4799:24)
    at F.fromData (seki-embed.js:4829:21)
    at Kt (seki-embed.js:6233:14)
    at Xr (seki-embed.js:6254:34)
    at seki-embed.js:6499:83
    at Array.forEach (<anonymous>)
```

Edit: Looks like `eventName` [here](https://github.com/adamreisnz/seki/blob/dd739a2f12599a984deb68efdb3dd6aae4a03ac1/src/classes/game.js#L548) should read `name`?

**Comment by adamreisnz** [comment]
Thank you, I've resolved the issue
